---
title: "Welcome to **DATA 202**"
subtitle: "Statistically Measuring and Modeling Social Justice"
---

::: column-screen-inset-right
| Part | Week | Day | Topics | Labs | Papers | Main reading |
|:---------:|:---------:|-----------|-----------|:---------:|:---------:|:---------:|
| I | [1](weeks/week01.html) | Wed, Jan 15 | [Introduction](weeks/week01-slides.html) | [Lab 0](computing.html) |  | [Case study 1](https://canvas.howard.edu/courses/59441/modules){target="_blank"} |
|  | [2](weeks/week02.html) | Wed, Jan 22 | [Foundations](weeks/week02-slides.html) |  |  | [Pelham (2013, ch. 1)](https://www.dropbox.com/scl/fi/8mxvv4hdi43n1ollipp9g/_Pelham-B.-2013-.-Intermediate-Statistics-A-Conceptual-Course-Ch.-1-copy.pdf?rlkey=zltrtv567j94bs6ookj8sy8fe&dl=0){target="_blank"} |
|  | [3](weeks/week03.html) | Wed, Jan 29 | [Theory construction](weeks/week03-slides.html) |  |  | [Shore (2008)](https://www.dropbox.com/scl/fi/t8istqr21aop2w4kcefgv/Shore-E.-2008-.-Quantification.pdf?rlkey=ge83d51f3r9h0fra0znt7bj40&dl=0){target="_blank"} |
|  | [4](weeks/week04.html) | Wed, Feb 5 | [Probability theory](weeks/week04-slides.html) |  |  | Case study 2: [pt. 1](cases/case02-pt1.html) & [pt. 2](cases/case02-pt2.html) |
| II | [5](weeks/week05.html) | Wed, Feb 12 | [Univariate analysis](weeks/week05-slides.html) | [Lab 1](labs/lab1.html) |  | [Frisby (2024)](https://www.dropbox.com/scl/fi/b7sgjud5lm8z61kaw0gzr/frisby-2024-critical-quantitative-literacy-an-educational-foundation-for-critical-quantitative-research.pdf?rlkey=3e03lvj4ykidqo7jpgocmho8o&dl=0){target="_blank"} |
|  | [6](weeks/week06.html) | Wed, Feb 19 | [Bivariate analysis](weeks/week06-slides.html) |  |  | [Zuberi (2000)](https://www.dropbox.com/scl/fi/rthwk2rmaiog1c2ebwrmw/Zubieri-T.-2000-.-Problems-in-the-Quantification-of-Race.pdf?rlkey=9yyoxq3tksv5wca7rhf7fd3ye&dl=0){target="_blank"} |
|  | [7](weeks/week07.html) | Wed, Feb 26 | [Exploratory analysis](weeks/week07-slides.html) |  | [Paper 1](papers/paper1.html) | [Kvam et al. (2015)](https://www.dropbox.com/scl/fi/9bgd5julpy146ezwa9p0n/Categorical-Data_Chapter-9.pdf?rlkey=d4rieih0givu3l0vq2m9tmf4i&dl=0){target="_blank"} |
|  |  | Wed, Mar 5 | Spring Break |  |  |  |
|  | [8](weeks/week08.html) | Wed, Mar 12 | [Hypothesis testing](weeks/week08-slides.html) |  |  | [Garcia et al. (2018)](https://www.dropbox.com/scl/fi/n6jvv486pnp3rqvyqwjf6/Garcia-et-al-2018-.-QuantCrit-rectifying-quantitative-methods-through-critical-race-theory.pdf?rlkey=ye9v5rwxfwp7apoeu56rf9ab7&dl=0){target="_blank"} |
| III | [9](weeks/week09.html) | Wed, Mar 19 | [Notes on causal theories](weeks/week09-slides.html) |  |  | Case study 3 files |
|  | [10](weeks/week10.html) | Wed, Mar 26 | [Modeling social in/justice](weeks/week10-slides.html) | [Lab 2](labs/lab2.html) |  | [Everitt & Horthon (2011), Ch. 1](https://www.dropbox.com/scl/fi/cqtdj7lhpluhbs93621ve/Everitt-Horthorn-nd-.-An-Intro-to-Applied-Multi-Stat-with-R-by-Everitt-et-al.pdf?rlkey=92fqtz4icbgkd5969fabs4mgj&dl=0){target="_blank"} |
|  | [11](weeks/week11.html) | Wed, Apr 2 | [Regression](weeks/week11-slides.html) |  |  | [Ward (2013)](https://www.dropbox.com/scl/fi/fdz9yaqycl5td9ljsdg9v/Ward-2013-.-Spurious-Correlations.pdf?rlkey=qsnwpgxqqkdx1yyq9q2d9z1a7&dl=0){target="_blank"} |
|  | [12](weeks/week12.html) | Wed, Apr 9 | [Multiple variable analysis](weeks/week12-slides.html) |  |  | [Everitt & Horthon (2011), Ch. 2](https://www.dropbox.com/scl/fi/cqtdj7lhpluhbs93621ve/Everitt-Horthorn-nd-.-An-Intro-to-Applied-Multi-Stat-with-R-by-Everitt-et-al.pdf?rlkey=92fqtz4icbgkd5969fabs4mgj&dl=0){target="_blank"} |
| IV | [13](weeks/week13.html) | Wed, Apr 16 | [Writing critical statistics](weeks/week13-slides.html) |  | [Paper 2](papers/paper2.html) | [Stroup (2015)](https://www.dropbox.com/scl/fi/5hql18kilxugw3tlr40eg/Rethinking_the_Analysis_of_Non-Normal_Data_in_Plan.pdf?rlkey=yce4t6mfy4gtqomvzxav1y7lc&dl=0){target="_blank"} |
|  | [14](weeks/week14.html) | Wed, Apr 23 | [Statistical learning](weeks/week14-slides.html) |  |  |  |
:::

## Site Description

The pages on this site outline the coding components of the **DATA 202: Statistically Measuring and Modeling Social Justice** course at Howard University, taught by me: [Professor Nathan Alexander](https://professornaite.github.io).

The information on this page will serve as a technical <u>*companion*</u> to our Canvas site.

This page will support you in our course in the following ways:

-   This page will help you work with data sets and complete small tasks over time.

-   This page will walk you through the measurement aspect of research questions relevant to modeling issues of social justice.

-   This page will help you integrate mathematical ideas and technical formulas into your work.

-   This page will support your use of theory in your statistical practice, and increase your ability to document reproducible code around a set of research questions.

Our canvas site ([click here](https://canvas.howard.edu/courses/59441)) contains readings and is where you will submit <u>all</u> assignments.

This site should be paired with Canvas to help you complete course assignments.

And just for good measure: all assignments should be turned in via Canvas.

*When turning in assignments on Canvas*:

-   Generally, **PDF submissions** are the way to go.

-   I will not download any files not uploaded to **Canvas**. I will only click on a clearly visible Github repository (i.e., no shortened or bit.ly links). Article citations that include DOIs are preferred.

-   We will discuss **RMarkdown files** which integrate code, formulas, and text. The .Rmd file is actually how I created some pages on this site for our course, and it is a great way to communicate your technical ideas.

-   This is a Canvas *companion* site/page (I'll use these terms interchangeably) and it will serve as your guide to completing all technical assignments.

### Giving credit

The below websites were used when building this course site. I am thankful for those who have provided open source resources such as these that allow others to generate new products.

-   Duke University's STAT 101 [course site](https://sta101-f23.github.io/)

-   Noli Brazil's [Quantitative Methods in Community Research](https://crd150.github.io/index.html)

### Next up: Overview

The overview in the next section will walk you through the technical flow of the course.

Like this section, a preview of forthcoming topics will be included at the bottom of each page; this means that you can treat this site like a textbook that you would read in order from start to finish. Though I encourage you to explore what else is out there and make use of other resources. That said, submissions should follow the formal guidelines outlined on our syllabus, Canvas, and this site.

-   The **syllabus** provides a high-level view of the course.

-   **Canvas** is the go-to for submissions and provides readings and assignments.

-   This **course site** provides technical items and code to help you complete your assignments.

Coming up next are the four parts of the course and an overview of the assignments for the term. Course topics are outlined in more detail and integrated into the assignment submission schedule on the next page; see you over there!
